# Generated by Django 6.0.1 on 2026-01-21 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_configuracionagenda_diabloqueado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracionagenda',
            old_name='domingo',
            new_name='trabaja_domingo',
        ),
        migrations.RenameField(
            model_name='configuracionagenda',
            old_name='jueves',
            new_name='trabaja_jueves',
        ),
        migrations.RenameField(
            model_name='configuracionagenda',
            old_name='lunes',
            new_name='trabaja_lunes',
        ),
        migrations.RenameField(
            model_name='configuracionagenda',
            old_name='martes',
            new_name='trabaja_martes',
        ),
        migrations.RenameField(
            model_name='configuracionagenda',
            old_name='miercoles',
            new_name='trabaja_miercoles',
        ),
        migrations.RenameField(
            model_name='configuracionagenda',
            old_name='sabado',
            new_name='trabaja_sabado',
        ),
        migrations.RenameField(
            model_name='configuracionagenda',
            old_name='viernes',
            new_name='trabaja_viernes',
        ),
        migrations.RemoveField(
            model_name='configuracionagenda',
            name='duracion_turno',
        ),
        migrations.AddField(
            model_name='configuracionagenda',
            name='intervalo_minutos',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='configuracionagenda',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='configuracionagenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='diabloqueado',
            name='motivo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
