# Generated by Django 6.0.1 on 2026-01-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_rename_domingo_configuracionagenda_trabaja_domingo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='aceptado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turno',
            name='comentario_ludmila',
            field=models.TextField(blank=True, help_text='Comentario visible para el cliente'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='nombre_completo',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='turno',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
