# Generated by Django 6.0.1 on 2026-01-21 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_turno_aceptado_turno_comentario_ludmila_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='nombre_completo',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='turno',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono solo puede contener números.', regex='^\\d+$')]),
        ),
    ]
