# Generated by Django 6.0.1 on 2026-01-21 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alter_turno_nombre_completo_alter_turno_telefono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turno',
            name='nombre_completo',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='turno',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
