# Generated by Django 4.2.29 on 2026-05-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_servicio_turno_cancelado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['categoria', 'orden', 'nombre'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('pestanas', 'Pestañas'), ('cejas', 'Cejas')], default='pestanas', max_length=20),
        ),
    ]
