# Generated by Django 4.2.29 on 2026-05-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_unique_slot_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='comentario',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
