# Generated by Django 4.2.29 on 2026-05-23 17:38

import datetime
from django.db import migrations, models


def crear_bloques_iniciales(apps, schema_editor):
    ConfiguracionAgenda = apps.get_model('reservas', 'ConfiguracionAgenda')
    HorarioBloque = apps.get_model('reservas', 'HorarioBloque')

    config = ConfiguracionAgenda.objects.first()
    if not config:
        return

    dias_flags = [
        (0, config.trabaja_lunes),
        (1, config.trabaja_martes),
        (2, config.trabaja_miercoles),
        (3, config.trabaja_jueves),
        (4, config.trabaja_viernes),
        (5, config.trabaja_sabado),
        (6, config.trabaja_domingo),
    ]
    for dia_idx, trabaja in dias_flags:
        if trabaja:
            HorarioBloque.objects.create(
                dia=dia_idx,
                hora_inicio=config.hora_inicio,
                hora_fin=config.hora_fin,
                activo=True,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_seguridad_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioBloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día')),
                ('hora_inicio', models.TimeField(verbose_name='Desde')),
                ('hora_fin', models.TimeField(verbose_name='Hasta')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bloque horario',
                'verbose_name_plural': 'Bloques horarios',
                'ordering': ['dia', 'hora_inicio'],
            },
        ),
        migrations.RunPython(crear_bloques_iniciales, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='configuracionagenda',
            options={'verbose_name': 'Configuración global', 'verbose_name_plural': 'Configuración global'},
        ),
        migrations.RemoveField(
            model_name='configuracionagenda',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='configuracionagenda',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='configuracionagenda',
            name='trabaja_domingo',
        ),
        migrations.RemoveField(
            model_name='configuracionagenda',
            name='trabaja_jueves',
        ),
        migrations.RemoveField(
            model_name='configuracionagenda',
            name='trabaja_lunes',
        ),
        migrations.RemoveField(
            model_name='configuracionagenda',
            name='trabaja_martes',
        ),
        migrations.RemoveField(
            model_name='configuracionagenda',
            name='trabaja_miercoles',
        ),
        migrations.RemoveField(
            model_name='configuracionagenda',
            name='trabaja_sabado',
        ),
        migrations.RemoveField(
            model_name='configuracionagenda',
            name='trabaja_viernes',
        ),
        migrations.AlterField(
            model_name='configuracionagenda',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='configuracionagenda',
            name='intervalo_minutos',
            field=models.PositiveIntegerField(default=30, help_text='Minutos entre cada turno disponible (ej: 30, 45, 60).'),
        ),
        migrations.AlterField(
            model_name='diabloqueado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
